# Generated by Django 5.2.7 on 2025-10-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_latitude_remove_profile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
