# Generated by Django 5.2.7 on 2025-10-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='delivery_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
